# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf4fa0a165172c758ea21f05c491ca5c52853f0437a045a52df4554ffd9ebfddaeb8eb749d87d4b45e2bb854e9e57c7fb3067896d977d40b0ceef46143a16ea9

test:
  secret_key_base: 4b33ae27a43d986246793361ad29d2ae4c8fdf1e30aa84f3893da5586d2cbfba523b5a536f4d2beea1bb0fe0ce180572af11bf3b43dd3d6254afd931f8d4f74a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
